import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";
import DataProvider from "@/context/dataContext";
import Providers from "@/app/lib/providers";
  import { ToastContainer} from 'react-toastify';
import "react-toastify/dist/ReactToastify.css";
import { Slide, Bounce, Zoom, Flip } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Assignment-7 keen-keeper",

  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased `}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <Navbar />
          {children}
          <Footer />

          <ToastContainer

           position="top-center"
        autoClose={2000}
      
 
      

        transition={Zoom}
         
          />
        </Providers>
      </body>
    </html>
  );
}
